= let
    Source = Csv.Document(File.Contents(N/A Sensitive Data),
    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Grade", Int64.Type}, {"Quiz 1: Quiz 1: Introduction to Enterprise Modelling", type text}, {"Quiz 2: Quiz 2: From demand to supply", type text}, {"Quiz 3: Quiz 3: Merode", type text}, {"Quiz 4: Check your understanding: Course Grades System", type text}, {"Quiz 5: Quiz 4a: Basic EDG Quiz", type text}, {"Quiz 6: Quiz 4b: EDG Advanced Quizzes", type text}, {"Quiz 7: Preparing for exercise session 2", type text}, {"Quiz 8: Quiz 4c: Analyzing EDGs", type text}, {"Quiz 9: Quiz 5: OET", type text}, {"Quiz 10: Quiz 6a: FSM Quizzes", type text}, {"Quiz 11: Quiz 6b: Global Behaviour", type text}, {"Quiz 12: Preparation for Exercise Session 4", type text}, {"Quiz 13: Quiz 7b: FSMs - additional exercises", type text}, {"Quiz 14: Quiz 7: Attributes and Constraints", type text}, {"Quiz 15: Mid-Course Practice Test", type text}, {"Quiz 16: Quiz 8: Inheritance", type text}, {"Quiz 17: Chapter 9 Quiz", type text}, {"Quiz 18: Chapter 10 Quiz", type text}, {"Quiz 19: Chapter 11 Quiz", type text}, {"Quiz 20: Chapter 12 Quiz", type text}, {"Quiz (Avg)", Int64.Type}, {"Exercise Session 1: Exercise session 1", type text}, {"Exercise Session 2: Exercise Session 2", type text}, {"Exercise Session 3: Exercise session 3", type text}, {"Exercise Session 4: Exercise Session 4", type text}, {"Exercise Session 5: Exercise Session 5", type text}, {"Exercise Session 6: Exercise Session 6", type text}, {"Exercise Session 7: Exercise Session 7", type text}, {"Exercise Session 8: Exercise Session 8", type text}, {"Exercise Session (Avg)", Int64.Type}, {"Homework 1: Homework 1", type text}, {"Homework 2: Homework 2", type text}, {"Homework 3: Duplicate of 'Homework 2'", type text}, {"Homework (Avg)", Int64.Type}, {"Quiz-ExamPrep 1: Quizzes", type text}, {"Quiz-ExamPrep 2: Part of Duplicate FSMs - additional exercises'", type text}, {"Quiz-ExamPrep 3: Object Interaction", type text}, {"Quiz-ExamPrep 4: Duplicate of Part of 'Exercise: Commercial company'", type text}, {"Quiz-ExamPrep 5: Duplicate of 'Mid-Course Practice Test'", type text}, {"Quiz-ExamPrep 6: Quizzes part 2", type text}, {"Quiz-ExamPrep 7: Duplicate of 'FSMs - additional exercises'", type text}, {"Quiz-ExamPrep (Avg)", Int64.Type}, {"ES-ExamPrep 1: Duplicate of 'Exercise Session 1'", type text}, {"ES-ExamPrep 2: Duplicate of 'Exercise Session 2'", type text}, {"ES-ExamPrep 3: Duplicate of 'Exercise session 3'", type text}, {"ES-ExamPrep 4: Duplicate of 'Exercise Session 4'", type text}, {"ES-ExamPrep 5: Duplicate of 'Exercise Session 6'", type text}, {"ES-ExamPrep 6: Duplicate of 'Exercise Session 7'", type text}, {"ES-ExamPrep 7: Duplicate of 'Exercise Session 8'", type text}, {"ES-ExamPrep (Avg)", Int64.Type}, {"Enrollment Track", type text}, {"Verification Status", type text}, {"Certificate Eligible", type text}, {"Certificate Delivered", type text}, {"Certificate Type", type text}, {"Enrollment Status", type text}, {"Student", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Grade", "Quiz (Avg)", "Exercise Session (Avg)", "Homework 1: Homework 1", "Homework 2: Homework 2", "Homework 3: Duplicate of 'Homework 2'", "Homework (Avg)", "Quiz-ExamPrep 1: Quizzes", "Quiz-ExamPrep 2: Part of Duplicate FSMs - additional exercises'", "Quiz-ExamPrep 3: Object Interaction", "Quiz-ExamPrep 4: Duplicate of Part of 'Exercise: Commercial company'", "Quiz-ExamPrep 5: Duplicate of 'Mid-Course Practice Test'", "Quiz-ExamPrep 6: Quizzes part 2", "Quiz-ExamPrep 7: Duplicate of 'FSMs - additional exercises'", "Quiz-ExamPrep (Avg)", "ES-ExamPrep 1: Duplicate of 'Exercise Session 1'", "ES-ExamPrep 2: Duplicate of 'Exercise Session 2'", "ES-ExamPrep 3: Duplicate of 'Exercise session 3'", "ES-ExamPrep 4: Duplicate of 'Exercise Session 4'", "ES-ExamPrep 5: Duplicate of 'Exercise Session 6'", "ES-ExamPrep 6: Duplicate of 'Exercise Session 7'", "ES-ExamPrep 7: Duplicate of 'Exercise Session 8'", "ES-ExamPrep (Avg)", "Enrollment Track", "Verification Status", "Certificate Eligible", "Certificate Delivered", "Certificate Type", "Enrollment Status"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"Quiz 1: Quiz 1: Introduction to Enterprise Modelling", "Quiz 1: Introduction to Enterprise Modelling"}, {"Quiz 2: Quiz 2: From demand to supply", "Quiz 2: From demand to supply"}, {"Quiz 3: Quiz 3: Merode", "Quiz 3: Merode"}, {"Quiz 5: Quiz 4a: Basic EDG Quiz", "Quiz 5: Basic EDG Quiz"}, {"Quiz 6: Quiz 4b: EDG Advanced Quizzes", "Quiz 6: EDG Advanced Quizzes"}, {"Quiz 8: Quiz 4c: Analyzing EDGs", "Quiz 8: Analyzing EDGs"}, {"Quiz 9: Quiz 5: OET", "Quiz 9: OET"}, {"Quiz 10: Quiz 6a: FSM Quizzes", "Quiz 10: FSM Quizzes"}, {"Quiz 11: Quiz 6b: Global Behaviour", "Quiz 11: Global Behaviour"}, {"Quiz 13: Quiz 7b: FSMs - additional exercises", "Quiz 13: FSMs - additional exercises"}, {"Quiz 14: Quiz 7: Attributes and Constraints", "Quiz 14: Attributes and Constraints"}, {"Quiz 16: Quiz 8: Inheritance", "Quiz 16: Inheritance"}, {"Exercise Session 1: Exercise session 1", "Exercise Session 1:"}, {"Exercise Session 2: Exercise Session 2", "Exercise Session 2:"}, {"Exercise Session 3: Exercise session 3", "Exercise Session 3:"}, {"Exercise Session 4: Exercise Session 4", "Exercise Session 4:"}, {"Exercise Session 5: Exercise Session 5", "Exercise Session 5:"}, {"Exercise Session 6: Exercise Session 6", "Exercise Session 6:"}, {"Exercise Session 7: Exercise Session 7", "Exercise Session 7:"}, {"Exercise Session 8: Exercise Session 8", "Exercise Session 8:"}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Exercise Session 1:", "Exercise Session 2:", "Exercise Session 3:", "Exercise Session 4:", "Exercise Session 5:", "Exercise Session 6:", "Exercise Session 7:", "Exercise Session 8:", "Student"}, "Attribute", "Value"),
    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Quiz"}, {"Value", "Score"}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns1",{"Exercise Session 1:", "Exercise Session 2:", "Exercise Session 3:", "Exercise Session 4:", "Exercise Session 5:", "Exercise Session 6:", "Exercise Session 7:", "Exercise Session 8:"}),
    #"Replaced Value" = Table.ReplaceValue(#"Removed Columns1","Not Attempted","",Replacer.ReplaceText,{"Score"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",".",",",Replacer.ReplaceText,{"Score"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Replaced Value1",{{"Score", Percentage.Type}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type1", "Student", "Student - Copy"),
    #"Extracted Last Characters" = Table.TransformColumns(#"Duplicated Column", {{"Student - Copy", each Text.End(_, 3), type text}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Extracted Last Characters",{{"Student - Copy", "StudentOrd"}}),
    #"Replaced Value2" = Table.ReplaceValue(#"Renamed Columns2","t","",Replacer.ReplaceText,{"StudentOrd"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Replaced Value2",{{"StudentOrd", Int64.Type}})
in
    #"Changed Type2"